import type { User, Apartment, Transaction } from "./types"

export const mockUsers: User[] = [
  {
    id: "1",
    email: "admin@zubaihomes.com",
    password: "admin123",
    role: "admin",
    name: "Admin User",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    email: "viewer@zubaihomes.com",
    password: "viewer123",
    role: "viewer",
    name: "Viewer User",
    createdAt: new Date("2024-01-01"),
  },
]

export const mockApartments: Apartment[] = [
  {
    id: "1",
    name: "Apartment 101",
    address: "Dubai Marina Tower A, Floor 10",
    rentalPrice: 75000,
    status: "occupied",
    currentTenant: "Mohammed Ahmed",
    leaseStartDate: new Date("2024-01-01"),
    leaseEndDate: new Date("2024-12-31"),
  },
  {
    id: "2",
    name: "Apartment 202",
    address: "Business Bay Complex B, Floor 20",
    rentalPrice: 85000,
    status: "occupied",
    currentTenant: "Sarah Khan",
    leaseStartDate: new Date("2024-02-01"),
    leaseEndDate: new Date("2025-01-31"),
  },
  {
    id: "3",
    name: "Apartment 305",
    address: "JBR Heights Tower C, Floor 30",
    rentalPrice: 95000,
    status: "vacant",
  },
  {
    id: "4",
    name: "Apartment 410",
    address: "Downtown Dubai Plaza D, Floor 41",
    rentalPrice: 120000,
    status: "occupied",
    currentTenant: "Ahmed Ali",
    leaseStartDate: new Date("2024-03-01"),
    leaseEndDate: new Date("2025-02-28"),
  },
]

export const mockTransactions: Transaction[] = [
  {
    id: "1",
    apartmentId: "1",
    type: "income",
    category: "Rent Payment",
    amount: 6250,
    description: "Monthly rent - January 2024",
    date: new Date("2024-01-05"),
    createdBy: "1",
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "2",
    apartmentId: "1",
    type: "expense",
    category: "Maintenance",
    amount: 800,
    description: "AC repair",
    date: new Date("2024-01-10"),
    createdBy: "1",
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "3",
    apartmentId: "2",
    type: "income",
    category: "Rent Payment",
    amount: 7083,
    description: "Monthly rent - February 2024",
    date: new Date("2024-02-05"),
    createdBy: "1",
    createdAt: new Date("2024-02-05"),
  },
  {
    id: "4",
    apartmentId: "2",
    type: "expense",
    category: "Utilities",
    amount: 450,
    description: "DEWA bill",
    date: new Date("2024-02-15"),
    createdBy: "1",
    createdAt: new Date("2024-02-15"),
  },
  {
    id: "5",
    apartmentId: "4",
    type: "income",
    category: "Rent Payment",
    amount: 10000,
    description: "Monthly rent - March 2024",
    date: new Date("2024-03-05"),
    createdBy: "1",
    createdAt: new Date("2024-03-05"),
  },
  {
    id: "6",
    apartmentId: "4",
    type: "expense",
    category: "Property Management",
    amount: 1200,
    description: "Management fee",
    date: new Date("2024-03-10"),
    createdBy: "1",
    createdAt: new Date("2024-03-10"),
  },
]
